apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitops-observability-demo
  namespace: gitops-demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-observability-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
