apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  description: GitOps application project for the EKS observability demo.

  sourceRepos:
    - https://github.com/fareez-lic/devops-eks-gitops-observability.git

  destinations:
    - namespace: gitops-demo
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
